### ISSUE TITLE
Can't submit function signature "mint(uint256 nonce, bytes32 challenge_digest)" to the directory

### ISSUE THREAD

**Issue by smarx** [ethereum-lists/4bytes#28]
I thought I'd help out by submitting signatures some hashes in https://github.com/ethereum-lists/4bytes/issues/25#issuecomment-396250160.

I tried via https://www.4byte.directory/submit/ to submit the signature `mint(uint256 nonce, bytes32 challenge_digest)`, but it seems to have been misinterpreted as `mint(int256,uint256,bytes32)`. My guess without reading code is that the "int" in "mint" was misinterpreted as a parameter.

**Comment by ligi** [comment]
thanks for the hint - cc @pipermerriam

**Comment by smarx** [comment]
FYI, perhaps the same problem with `mint(address _to, uint256 _amount)`. (Not 100% sure how this one was interpreted because I just got a 500.) This is also in the "top 20" list.

**Comment by ligi** [comment]
yea also getting 500 now - might be more instances of this: https://github.com/pipermerriam/ethereum-function-signature-registry/issues/30
Maybe I make a separate backend soon to decouple from this python stuff ;-)

**Comment by smarx** [comment]
Ah, I couldn't find the repo for the website. Should I open an issue over there so we can close this one?

**Comment by ligi** [comment]
that would be great!

**Comment by smarx** [comment]
Opened https://github.com/pipermerriam/ethereum-function-signature-registry/issues/31.

**Comment by pipermerriam** [comment]
Should be resolved.
