### ISSUE TITLE
Import data from Etherface

### ISSUE THREAD

**Issue by volsa** [ethereum-lists/4bytes#75]
Hi there 👋 
I'm the author of [Etherface](https://github.com/volsa/etherface), which currently hosts around 2.4 million signatures. One goal of Etherface was to provide these collected signatures back to the community at some point and I think now's a good time. Would you be interested in importing these signatures? If so, I'd be happy to provide a database dump.

**Comment by ligi** [comment]
Thanks for the offer - I am not sure though. Just checked the data quality by looking up 0x00000000 and there is a lot of garbage. So I would have to spend quite some time to maintain the ignore list (btw you might be interested in using it to clean up your data a bit)
Unfortunately this is time intensive and I do not have the time currently - thanks for the offer though.

**Comment by ligi** [comment]
PS: https://github.com/volsa/etherface/issues/18

**Comment by volsa** [comment]
Sure, no problem. Filtering garbage data is definitely something I should have planned and implemented retrospectively. Currently scraping these signatures is mostly naive RegEx matching, which defintely needs some changes. Anyways, closing this issue.
